### PR TITLE
MemConfig integration

### PR DESCRIPTION
**Pull request by cehteh**
I put this in its own branch now. still WIP. 

* MemConfig is integrated
* Benchmarks got some beef up
* While at it, changing the 'reserve()' code into a hot/cold path gives a *huge* performance boost.

### CODE REVIEW

**Comment by cehteh** [comment]
Actually this can be merged. I'll making new branches/PR's for upcoming changes.

**Comment by cehteh** [comment]
Note: while this is working fine I am thinking to implement this somewhat differently in future:

One trait per MemConfig thing (Capacity, SegmentSize, SegmentAndOffset, ....). Then ditch the PhantomData<C>. Each of these aspects can then be ZST's or Sized fields (example: Capacity needs only be stored when its costly to recalculate). This can as well give hints to the SegmentCache implementation.

So far this is just a brainfart. I need to play with that idea eventually.

**Comment by mccolljr** [comment]
Can you change the target branch to `master`? I will wait until changes have been finalized to push a new tagged version, but I'd like to use that as the main development branch.

**Review by mccolljr — CHANGES_REQUESTED** [review]
In order to resolve the conflicts from making the target branch `master`, you'll need to do:

`git rebase -i origin/master`

You can use this as your rebase plan:
```
d 8ec86e4 make SegVec const-generic
d 9664e02 SegVec::new can't be const because smallvec's new is non-const
d c94d100 Fix a bug where the truncate method improperly accounted for factor
d 0d61f9e Make some simple functions inline
pick dacb476 add mem_config.rs for different allocation policies
pick df4be67 comment wording
pick d7adac1 The MemConfig impls must be public
pick c52509d add 'debug_assert_config' for validating config parameters
pick 0ace025 integrate MemConfig into SegVec
pick c742855 fixing few clippy lints (some remain, to be addressed later)
pick 12a2a48 split 'reserve()' into a hot and a cold path and add capacity back
pick 4d656ab improve benchmarks
```

**Comment by mccolljr** [comment]
(I would have done this for you, but I would have had to force-push to a branch in your fork and I didn't feel right about doing that without asking first)

**Comment by cehteh** [comment]
rebase done, thanks for the plan. I wouldn't mind when you did that.

**Review by mccolljr — APPROVED** [review]
Thank you for your work on this.

**Pull request merged**
