### PR TITLE
impl `io::Write` for `SegVec<u8>`

### PR DESCRIPTION
**Pull request by vxpm**
very straightforward implementation of the `write` trait

### CODE REVIEW

**Comment by mccolljr** [comment]
Thank you for this - even though it's a very simple change, would you mind adding a test?

**Comment by vxpm** [comment]
sure! i'll change this implementation a bit, however. i think it can be optimized further with something like a `extend_from_slice`.

**Comment by vxpm** [comment]
i rebased this to be on top of #41 , not sure if it was a good decision - git is hard

**Comment by mccolljr** [comment]
Acknowledged - I should have some time later today to look this over

**Comment by mccolljr** [comment]
Once we finish up the review on #41 I can come back and merge this, but I want to fix up the potential safety issue over there first, then we can rebase this on the master branch and I can push it through :)

**Comment by mccolljr** [comment]
Now that #41 has been merged, can you rebase this on the master branch?

**Comment by vxpm** [comment]
done!

**Comment by mccolljr** [comment]
Thanks, merged!

**Pull request merged**
